application: nswi152
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: contents.html
  upload: contents\.html

- url: /presentation-output\.html
  static_files: presentation-output.html
  upload: presentation-output\.html

- url: /presentation-output1\.html
  static_files: presentation-output1.html
  upload: presentation-output1\.html

- url: /slide_config\.js
  static_files: slide_config.js
  upload: slide_config\.js

- url: /js
  static_dir: js

- url: /theme
  static_dir: theme

- url: /images
  static_dir: images
